/*
 * This source file was generated by the Gradle 'init' task
 */
package lab3ex2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    /**
     * Testa se a operação de soma está  correta.
     * Neste caso, soma 1 + 2 = 3.
     */
    @Test void testSoma() {
        Operacao op = Operacao.SOMA;
        assertEquals(3, op.calcula(1, 2));
    }

    /**
     * Testa se a operação de subtração está  correta.
     * Neste caso, soma 3 - 2 = 1.
     */
    @Test void testSubtracao() {
        Operacao op = Operacao.SUBTRACAO;
        assertEquals(1, op.calcula(3, 2));
    }

    /**
     * Testa se a operação de multiplicação está  correta.
     * Neste caso, multiplica 2 * 3 = 6.
     */
    @Test void testMultiplicacao() {
        Operacao op = Operacao.MULTIPLICACAO;
        assertEquals(6, op.calcula(2, 3));
    }

     /**
     * Testa se a operação de divisão está  correta.
     * Neste caso, divide 6 / 3 = 2.
     */
    @Test void testDivisao() {
        Operacao op = Operacao.DIVISAO;
        assertEquals(2, op.calcula(6, 3));
    }

}