/*
 * This source file was generated by the Gradle 'init' task
 */
package lab3ex1;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testAddTitulo() {
        SistemaFilmes sistema = new SistemaFilmes();
        Filme filme1 = new Filme("Filme A", 8.5, "Musical");
        Filme filme2 = new Filme("Filme B", 7.2, "Drama");
        Filme filmeRepetido = new Filme("Filme A", 6.0, "Comédia");

        assertTrue(sistema.addTitulo(filme1));
        assertTrue(sistema.addTitulo(filme2));
        assertFalse(sistema.addTitulo(filmeRepetido));
    }

    @Test
    void testMedianaNotas() {
        SistemaFilmes sistema = new SistemaFilmes();
        sistema.addTitulo(new Filme("Filme A", 8.0, "Ação"));
        sistema.addTitulo(new Filme("Filme B", 7.0, "Drama"));
        sistema.addTitulo(new Filme("Filme C", 9.0, "Ficção"));

        assertEquals(8.0, sistema.medianaNotas());

        sistema.addTitulo(new Filme("Filme D", 6.0, "Suspense"));
        assertEquals(7.5, sistema.medianaNotas());
    }

    @Test
    void testMedianaNotasListaVazia() {
        SistemaFilmes sistema = new SistemaFilmes();
        assertEquals(-1, sistema.medianaNotas());
    }
}

