/*
 * This source file was generated by the Gradle 'init' task
 */
package lab3ex1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Filme filme1 = new Filme("Mamma Mia!", 9.5, "Musical");
        Filme filme2 = new Filme("The Godfather", 8.5, "Drama");
        Filme filme3 = new Filme("The Matrix", 7.5, "Ficção");
        SistemaFilmes sistema = new SistemaFilmes();
        sistema.addTitulo(filme1);
        sistema.addTitulo(filme2);
        sistema.addTitulo(filme3);
        boolean res = sistema.addTitulo(filme1);
        System.out.println(res);
        // Expected false
        System.out.println(sistema.medianaNotas());
        // Expected 8.5
        

    }
}
