/*
 * This source file was generated by the Gradle 'init' task
 */
package lab3ex2;

import java.util.Scanner;

public class App {


/**
 * Lê um input String de operação
 * Realiza a operação e imprime o resultado
 *
 * @param args Command-line arguments (not used in this application).
 */

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String inputOperacao = sc.next();
        Operacao op = Operacao.valueOf(inputOperacao);
        double res = op.calcula(sc.nextInt(), sc.nextInt());
        System.out.println(res);
    }
}
