/*
 * This source file was generated by the Gradle 'init' task
 */
package atividadelab1;
// import java.util.Scanner;

// import atividadelab1.AdivinhaNumero;

public class App {
    
    public static void main(String[] args) {
        AdivinhaNumero jogo = new AdivinhaNumero();
        boolean acertou = false;

        System.out.println("🎲 Bem-vindo ao Jogo da Adivinhação!");
        System.out.println("Tente adivinhar um número entre 1 e 100.");
        while (!acertou) {
            jogo.tentativas++;
            System.out.print("Digite seu palpite: ");
            jogo.fazPalpite();
            acertou = jogo.verificaPalpite();
            jogo.imprimeTentativas();
        }
    }

}
